# On-Site Version 4.0
# Configure single sign on here

version: "3.6"

services:
  ccdc-identity:
    environment:
      - OnSiteLoginSetup__EnableSingleSignOn=true
      - OnSiteLoginSetup__EnableFormBasedLogin=true
      
      - ThirdPartyCredentials__Authority=<Authority>
      - ThirdPartyCredentials__ClientId=<Client Id>
      - ThirdPartyCredentials__ClientSecret=<Client Secret>
      - ThirdPartyCredentials__CallbackPath=/Identity/signin-oidc
      - ThirdPartyCredentials__DisplayName=<Name of SSO provider. Eg. Microsoft>
