# On-Site Version 4.0
version: "3.6"

services:
  webcsd:
    environment:
      - CsdRepository__SketcherFeatures__1=Proteins

  webcsdbackend:
    environment:
      - ServiceSettings__Databases__1__Name=PDB Database
      - ServiceSettings__Databases__1__DbeName=pdb
      - ServiceSettings__Databases__1__ConnectionString=dbe

  ccdc-csd-substructuresearch:
    environment:
      - SubstructureSearchDatabaseConfiguration__Databases__1__Name=pdb
      - SubstructureSearchDatabaseConfiguration__Databases__1__ReadConnectionString=${DB_CONNECTIONSTRING};SearchPath=structure_optimisation;Database=${CSD_DATABASE}
      - SubstructureSearchDatabaseConfiguration__Databases__1__WriteConnectionString=${DB_CONNECTIONSTRING};SearchPath=structure_optimisation;Database=${CSD_DATABASE}

  ccdc-csd-deposition:
    environment:
      - DepositionDatabaseConfiguration__Databases__1__Name=pdb
      - DepositionDatabaseConfiguration__Databases__1__ReadConnectionString=${DB_CONNECTIONSTRING};SearchPath=pdb_schema;Database=${CSD_DATABASE}
      - DepositionDatabaseConfiguration__Databases__1__WriteConnectionString=${DB_CONNECTIONSTRING};SearchPath=pdb_schema;Database=${CSD_DATABASE}

  ccdc-csd-textnumericsearch:
    environment:
      - PdbReadConnection=${DB_CONNECTIONSTRING};SearchPath=pdb_schema;Database=${CSD_DATABASE}
      - DatabaseConfiguration__Databases__1__Name=pdb
      - DatabaseConfiguration__Databases__1__SettingsKey=PdbReadConnection

  ccdc-csd-unitcellsearch:
    environment:
      - UnitCellDatabaseConfiguration__Databases__1__Name=pdb
      - UnitCellDatabaseConfiguration__Databases__1__ReadConnectionString=${DB_CONNECTIONSTRING};SearchPath=pdb_cell_optimisation;Database=${CSD_DATABASE}
      - UnitCellDatabaseConfiguration__Databases__1__WriteConnectionString=${DB_CONNECTIONSTRING};SearchPath=pdb_cell_optimisation;Database=${CSD_DATABASE}