# Configure local database volumes here

version: "3.6"

services:
  webcsd:
    environment:      
      - LoginPageSetup__EnableSSO=true
      - LoginPageSetup__EnableFormBasedLogin=true
      
      - ThirdPartyCredentials__Authority=<Authority>
      - ThirdPartyCredentials__ClientId=<Client Id>
      - ThirdPartyCredentials__ClientSecret=<Client Secret>
      - ThirdPartyCredentials__CallbackPath=<CallbackPath>
      - ThirdPartyCredentials__DisplayName=<Name of SSO provider. Eg. Microsoft>