version: "3.6"

services:
  webcsd:
    environment:
      - CsdRepository__ServiceLocation=webcsdbackend
      - CspRepository__ServiceLocation=webcsd-theory
      - CsdRepository__SketcherFeatures__1=Proteins
   
  webcsdbackend:
    environment:
      - CCDC_LICENSING_CONFIGURATION=${CCDC_LICENSING_CONFIGURATION}
      - ServiceSettings__Databases__1__Name=PDB Database
      - ServiceSettings__Databases__1__DbeName=pdb
      - ServiceSettings__Databases__1__ConnectionString=dbe

  ccdc-csd-substructuresearch:
    environment:
      - PdbReadConnection=${CSD_DB_CONNECTIONSTRING};SearchPath=structure_optimisation
      - SubstructureSearchDatabaseConfiguration__Databases__1__Name=pdb
      - SubstructureSearchDatabaseConfiguration__Databases__1__SettingsKey=PdbReadConnection

  ccdc-csd-deposition:
    environment:
      - DepositionPdbReadConnection=${CSD_DB_CONNECTIONSTRING};SearchPath=pdb_schema
      - DatabaseConfiguration__Databases__1__Name=pdb
      - DatabaseConfiguration__Databases__1__SettingsKey=DepositionPdbReadConnection

  ccdc-csd-textnumericsearch:
    environment:
      - PdbReadConnection=${CSD_DB_CONNECTIONSTRING};SearchPath=pdb_schema
      - DatabaseConfiguration__Databases__1__Name=pdb
      - DatabaseConfiguration__Databases__1__SettingsKey=PdbReadConnection


  ccdc-csd-unitcellsearch:
    environment:
      - UnitCellPdbReadConnection=${CSD_DB_CONNECTIONSTRING};SearchPath=pdb_cell_optimisation
      - DatabaseConfiguration__Databases__1__Name=pdb
      - DatabaseConfiguration__Databases__1__SettingsKey=UnitCellPdbReadConnection