# On-Site Version 4.0
# Configure local database volumes here for CSD-Theory installations.

version: "3.6"

services:
  csd-platform:
    ports:
      - ${PLATFORM_PORT}:8443
      # This is required for csd theory ingestion python script to work
      #- 80:8080

  webcsdbackend:
    volumes:
      - /path/to/CSD-Theory Landscape Database:/csd-data/CSPLandscape.csdsqlx
    environment:
      - ServiceSettings__Databases__2__Name=CSP Database
      - ServiceSettings__Databases__2__ConnectionString=/csd-data/CSPLandscape.csdsqlx
      - ServiceSettings__Databases__2__Speciality__0=CSP

  webcsd:
    volumes:
      - ./path/to/structure/files:/structure-files

  webcsd-theory:
    volumes:
      - /path/to/CSD-Theory Metadata Database:/app/CSPDatabase.db
      - /path/to/CSD-Theory Landscape Database:/app/databases/CSPLandscape.csdsqlx
    environment:
      - ReportSettings__CspStructureDatabaseConnectionString=/app/databases/CSPLandscape.csdsqlx