version: "3.6"

services:
  webcsd:
    environment:
      - CsdRepository__SearchServiceLocation=http://ccdc-csd-searchservice:${WEBCSD_PORT}/
      - CsdRepository__PagedResultLocation=http://ccdc-csd-searchservice:${WEBCSD_PORT}/
      - CsdRepository__RequestEntriesServiceLocation=http://csd-request-entry:${WEBCSD_PORT}/
      - CsdRepository__ChemicalDiagramImageLocation=http://csd-request-entry:${WEBCSD_PORT}/
      - CsdRepository__ChemicalStructureMol2Location=http://csd-request-entry:${WEBCSD_PORT}/
      - CsdRepository__AtomEquivalencesLocation=http://csd-request-entry:${WEBCSD_PORT}/
      - CsdRepository__FormulaSearchServiceLocation=http://ccdc-csd-searchservice:${WEBCSD_PORT}/
      - CsdRepository__StructureSimilaritySearchServiceLocation=http://ccdc-csd-searchservice:${WEBCSD_PORT}/
      - CsdRepository__UnitCellSearchLocation=http://ccdc-csd-searchservice:${WEBCSD_PORT}/
      - CsdRepository__ServiceLocation=webcsdbackend:${WEBCSD_PORT}
      - ASPNETCORE_URLS=http://+:${WEBCSD_PORT}
      - CspRepository__ServiceLocation=webcsd-theory:${WEBCSD_PORT}
    expose:
      - ${WEBCSD_PORT}
    healthcheck: 
      test: "curl --fail --silent --show-error --connect-timeout 5 --max-time 5 http://localhost:${WEBCSD_PORT}/health/ready"

  webcsdbackend:
    environment:
      - ASPNETCORE_URLS=http://+:${WEBCSD_PORT}
    expose:
      - ${WEBCSD_PORT}
    healthcheck: 
      test: "curl --fail --silent --show-error --connect-timeout 5 --max-time 5 http://localhost:${WEBCSD_PORT}/health/ready"
 
  database-server:
    expose:
      - 5432
      
  ccdc-csd-substructuresearch:
    environment:
      - FingerprintCalculationService=http://ccdc-csd-fingerprint:${WEBCSD_PORT}
      - ResultsStoreService=http://ccdc-csd-resultstore:${WEBCSD_PORT}
      - DepositionService=http://ccdc-csd-deposition:${WEBCSD_PORT}
      - SubstructureFilterService=http://ccdc-csd-substructure-filter:${WEBCSD_PORT}
      - ASPNETCORE_URLS=http://+:${WEBCSD_PORT}
    expose:
      - ${WEBCSD_PORT}
    healthcheck: 
      test: "curl --fail --silent --show-error --connect-timeout 5 --max-time 5 http://localhost:${WEBCSD_PORT}/health/ready"
      
  ccdc-csd-deposition:
    environment:
      - ASPNETCORE_URLS=http://+:${WEBCSD_PORT}
    expose:
      - ${WEBCSD_PORT}
    healthcheck: 
      test: "curl --fail --silent --show-error --connect-timeout 5 --max-time 5 http://localhost:${WEBCSD_PORT}/health/ready"
      

  ccdc-csd-textnumericsearch:
    environment:      
      - ASPNETCORE_URLS=http://+:${WEBCSD_PORT}
    expose:
      - ${WEBCSD_PORT}
    healthcheck: 
      test: "curl --fail --silent --show-error --connect-timeout 5 --max-time 5 http://localhost:${WEBCSD_PORT}/health/ready"
      
  ccdc-csd-searchservice:
    environment:
      - TextNumericSearchService=http://ccdc-csd-textnumericsearch:${WEBCSD_PORT}/
      - SubstructureSearchService=http://ccdc-csd-substructuresearch:${WEBCSD_PORT}/
      - QueryIdGeneratorService=http://ccdc-csd-resultstore:${WEBCSD_PORT}/
      - PagedResultsService=http://ccdc-csd-resultstore:${WEBCSD_PORT}/
      - FormulaSearchService=http://ccdc-csd-formulasearch:${WEBCSD_PORT}/
      - StructureSimilaritySearchService=http://ccdc-csd-similaritysearch:${WEBCSD_PORT}/
      - UnitCellSearchService=http://ccdc-csd-unitcellsearch:${WEBCSD_PORT}/
      - ASPNETCORE_URLS=http://+:${WEBCSD_PORT}
    expose:
      - ${WEBCSD_PORT}
    healthcheck: 
      test: "curl --fail --silent --show-error --connect-timeout 5 --max-time 5 http://localhost:${WEBCSD_PORT}/health/ready"

  csd-request-entry:
    environment:
      - CrystalStructureExportService=http://ccdc-csd-crystal-structure-export:${WEBCSD_PORT}
      - DepositionService=http://ccdc-csd-deposition:${WEBCSD_PORT}
      - ASPNETCORE_URLS=http://+:${WEBCSD_PORT}
    expose:
      - ${WEBCSD_PORT}
    healthcheck: 
      test: "curl --fail --silent --show-error --connect-timeout 5 --max-time 5 http://localhost:${WEBCSD_PORT}/health/ready"
 
  ccdc-csd-formulasearch:
    environment:
      - ASPNETCORE_URLS=http://+:${WEBCSD_PORT}
    expose:
      - ${WEBCSD_PORT}
    healthcheck: 
      test: "curl --fail --silent --show-error --connect-timeout 5 --max-time 5 http://localhost:${WEBCSD_PORT}/health/ready"

  ccdc-csd-unitcellsearch:
    environment:
      - UnitCellNiggliReducedCellCalculationService=http://ccdc-csd-reducedcell-calculation-service:${WEBCSD_PORT}
      - UnitCellReducedCellCalculationService=http://ccdc-csd-reducedcell-calculation-service:${WEBCSD_PORT}
      - ASPNETCORE_URLS=http://+:${WEBCSD_PORT}
    expose:
      - ${WEBCSD_PORT}
    healthcheck: 
      test: "curl --fail --silent --show-error --connect-timeout 5 --max-time 5 http://localhost:${WEBCSD_PORT}/health/ready"
      
  ccdc-csd-resultstore:
    environment:
      - ASPNETCORE_URLS=http://+:${WEBCSD_PORT}
    expose:
      - ${WEBCSD_PORT}
    healthcheck: 
      test: "curl --fail --silent --show-error --connect-timeout 5 --max-time 5 http://localhost:${WEBCSD_PORT}/health/ready"
      
  ccdc-csd-similaritysearch:
    environment:
      - FingerprintChemicalDiagramCalculationService=http://ccdc-csd-fingerprint:${WEBCSD_PORT}
      - ASPNETCORE_URLS=http://+:${WEBCSD_PORT}
    expose:
      - ${WEBCSD_PORT}
    healthcheck: 
      test: "curl --fail --silent --show-error --connect-timeout 5 --max-time 5 http://localhost:${WEBCSD_PORT}/health/ready"
      
  ccdc-csd-substructure-filter:
    environment:
      - CCDC_SERVICE_PORT=${WEBCSD_PORT}
    expose:
      - ${WEBCSD_PORT}
    healthcheck: 
      test: "curl --fail --silent --show-error --connect-timeout 5 --max-time 5 http://localhost:${WEBCSD_PORT}/health/ready"
      
  ccdc-csd-crystal-structure-export:
    environment:
      - CCDC_SERVICE_PORT=${WEBCSD_PORT}
    expose:
      - ${WEBCSD_PORT}   
    healthcheck: 
      test: "curl --fail --silent --show-error --connect-timeout 5 --max-time 5 http://localhost:${WEBCSD_PORT}/health/ready"  
      
  ccdc-csd-reducedcell-calculation-service:
    environment:
      - CCDC_SERVICE_PORT=${WEBCSD_PORT}
    expose:
      - ${WEBCSD_PORT}          
    healthcheck: 
      test: "curl --fail --silent --show-error --connect-timeout 5 --max-time 5 http://localhost:${WEBCSD_PORT}/health/ready"

  ccdc-csd-fingerprint:
    environment:
      - CCDC_SERVICE_PORT=${WEBCSD_PORT}
    expose:
      - ${WEBCSD_PORT}
    healthcheck: 
      test: "curl --fail --silent --show-error --connect-timeout 5 --max-time 5 http://localhost:${WEBCSD_PORT}/health/ready"

  webcsd-theory:
    environment:
      - ReportSettings__CspServerUrl=localhost:${WEBCSD_PORT}
      - ASPNETCORE_URLS=http://+:${WEBCSD_PORT}
    expose:
      - ${WEBCSD_PORT}