# On-Site Version 4.0
# Configure local database volumes here for CSD-Theory installations.

version: "3.6"

services:
  csd-platform:
    ports:
      - ${PLATFORM_PORT}:8443
      # This is required for csd theory ingestion python scripts to work
      #- 80:8080

  webcsdbackend:
    volumes:
      - /path/to/database-1:/csd-data/database-1
      - /path/to/database-2:/csd-data/database-2
    environment:
      - ServiceSettings__Databases__2__Name=database-1
      - ServiceSettings__Databases__2__ConnectionString=/csd-data/database-1
      - ServiceSettings__Databases__3__Name=database-2
      - ServiceSettings__Databases__3__ConnectionString=/csd-data/database-2

  webcsd:
    volumes:
      - ./path/to/structure/files:/structure-files

  webcsd-theory:
    volumes:
      - /path/to/CSD-Theory Metadata Database:/app/CSPDatabase.db
      - /path/to/CSD-Theory Landscape Database:/app/databases/CSPLandscape.csdsqlx
    environment:
      - ReportSettings__CspStructureDatabaseConnectionString=/app/databases/CSPLandscape.csdsqlx